version: "3.8"

services:
  shopping-service:
    depends_on:
      - shopping-postgres
    image: "gbakradze/shopping-service"
    container_name: "shopping-service"
    ports:
      - 8081:8081
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shopping-postgres:5432/shoppingdb
      - SPRING_PROFILES_ACTIVE=testdata

  shopping-postgres:
    image: "postgres:14.4"
    container_name: "shopping-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shoppingdb