spring:
  application:
    name: shopping-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
server:
  port: 8081
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
shop:
  greeting: Welcome to the Space shop